### PR TITLE
Restart confd once Consul is good to go

### LINKED ISSUE #237: [confd] Make sure we restart confd once Consul is configured and up and running
Otherwise, confd might have to wait for the watchdog to restart it, if it failed
to startup too quickly

### PR DESCRIPTION
**Pull request by gozer**
Fixes #237

### CODE REVIEW

File: nubis/bin/consul-autojoin.sh [hunk 1]
```diff
@@ -158,6 +158,9 @@ service consul stop
 rm -rf /var/lib/consul/serf/*
 service consul start
 
+# Make sure confd starts with consul up and running
+service confd restart
```
Comment (limed) [inline nubis/bin/consul-autojoin.sh]: Assuming this works in ubuntu as well then looks good

**Comment by limed** [comment]
r+
